development:
  adapter: mysql2
  encoding: utf8
  database: ecc_development
  username: root
  password: 
  host: localhost
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: ecc_test
  username: root
  password: 
  host: localhost
  socket: /tmp/mysql.sock
  
production:
  adapter: mysql2
  encoding: utf8
  database: ecc_production
  username: root
  password: V[-A#Mlp
  host: localhost
  socket: /tmp/mysql.sock